### ISSUE TITLE
ログアウトのテストが通らない

### ISSUE THREAD

**Issue by MeJamoLeo** [MeJamoLeo/down_app_rails#7]
ログアウトのテストが通らない

_Originally posted by @MeJamoLeo in https://github.com/MeJamoLeo/down_app_rails/issues/2#issuecomment-658295989_

**Comment by MeJamoLeo** [comment]
流れを確認する

**Comment by MeJamoLeo** [comment]
やりたいこと：
　　ログアウト後にセッションのuser_idがなく，ログインリンクが表示されている状態．
現状：
　　セッションが残ってると言われる

**Comment by MeJamoLeo** [comment]
テストのこの部分を考えていく
```rb
    delete logout_path
    assert_not is_logged_in?
```

**Comment by MeJamoLeo** [comment]
ログアウトの実行部分

routes.rb
```rb
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'   ←これ

  resources :users
```
sessions_controller.rb
```rb
  def destroy
    log_out    ←これ
    redirect_to root_url
  end
```
sessions_helper.rb
```rb
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
```

**Comment by MeJamoLeo** [comment]
**ログイン状態を確認する部分**`assert_not is_logged_in?`
```rb
  def is_logged_in?
    !session[:user_id.nil?]
  end
```

!（sessionのuser_idの値が，なければ，true，あれば，faulse）
　　　　↓
sessionのuser_idの値が，なければ，faulse 　あれば，true

**Comment by MeJamoLeo** [comment]
**エラーの内容：**
```sh
FAIL["test_login_with_valid_information_followed_by_logout", UsersLoginTest, 1.613073999993503]
 test_login_with_valid_information_followed_by_logout#UsersLoginTest (1.61s)
        Expected true to be nil or false
        test/integration/users_login_test.rb:34:in `block in <class:UsersLoginTest>
```

**Comment by MeJamoLeo** [comment]
ログアウトの確認をする部分では特に問題はなかった．

ログアウトを実行する部分に問題がありそう

**Comment by MeJamoLeo** [comment]
分かりやすくするために．puts でsession.to_hashを表示するようにした
```rb
rails test
Running via Spring preloader in process 66304
Started with run options --seed 22200

  22/3: [===========                                                                            ] 13% Time: 00:00:01,  ETA: 00:00:13
 セッションの情報@test_helper： {"session_id"=>"d951577f4390adb946b2a921ca62869c", "user_id"=>762146111} 

 セッションの情報@sessions_controller{"session_id"=>"d951577f4390adb946b2a921ca62869c"} 

 セッションの情報@test_helper： {"session_id"=>"d951577f4390adb946b2a921ca62869c"} 
 FAIL["test_login_with_valid_information_followed_by_logout", UsersLoginTest, 1.947789000114426]
 test_login_with_valid_information_followed_by_logout#UsersLoginTest (1.95s)
        Expected true to be nil or false
        test/integration/users_login_test.rb:34:in `block in <class:UsersLoginTest>'

  22/7: [==========================                                                             ] 31% Time: 00:00:02,  ETA: 00:00:04
 セッションの情報@test_helper： {"session_id"=>"5b3cf236d3badf24858e371a8571ceee", "user_id"=>762146112} 
  22/22: [=====================================================================================] 100% Time: 00:00:02, Time: 00:00:02

Finished in 2.22670s
```

**Comment by MeJamoLeo** [comment]
試してみたこと：
　　デバッグ，デバッグ，デバッグ

分かったこと
：
　　`session_id`が違うぞ！！
